/*
 * @Author: zfz
 * @Date: 2022-03-23 09:36:01
 * @LastEditors: px
 * @LastEditTime: 2022-03-30 14:27:33
 * @Description: update
 */
const basic = [
   {
        childMenuList: null,
        icon: null,
        id: "6",
        level: 2,
        menuCode: "PROJECT_MANAGMENT",
        name: "项目管理",
        parentCode: "2",
        select: null,
        url: "/basic/projectManagement",
      },
      {
        childMenuList: null,
        icon: null,
        id: "7",
        level: 2,
        menuCode: "AGREEMENT_MANAGMENT",
        name: "合同管理",
        parentCode: "2",
        select: null,
        url: "/device/ledger",
      },
      {
        childMenuList: null,
        icon: null,
        id: "8",
        level: 2,
        menuCode: "ASSIGNMENT_TYPE_MANAGMENT",
        name: "任务类型管理",
        parentCode: "2",
        select: null,
        url: "/basic/projectTaskList",
      },
      {
        childMenuList: null,
        icon: null,
        id: "9",
        level: 2,
        menuCode: "ASSIGNMENT_ROLE_MANAGMENT",
        name: "任务角色管理",
        parentCode: "2",
        select: null,
        url: "/basic/proTastRuleMgt",
      },
      {
        childMenuList: null,
        icon: null,
        id: "10",
        level: 2,
        menuCode: "CUSTOMER_MANAGMENT",
        name: "客户管理",
        parentCode: "2",
        select: null,
        url: "/basic/clientMgt",
      },
      {
        childMenuList: null,
        icon: null,
        id: "11",
        level: 2,
        menuCode: "USER_MANAGMENT",
        name: "用户管理",
        parentCode: "2",
        select: null,
        url: "/basic/userMgt",
      },
      {
        childMenuList: null,
        icon: null,
        id: "24",
        level: 2,
        menuCode: "ROLE_MANAGMENT",
        name: "角色管理",
        parentCode: "2",
        select: null,
        url: "/basic/roleList",
      },
]
const project = [
    {
      childMenuList: null,
      icon: null,
      id: "12",
      level: 2,
      menuCode: "DAY_REPORT_MANAGMENT",
      name: "日报管理",
      parentCode: "2",
      select: null,
      url: "/project/daily",
    },
    {
      childMenuList: null,
      icon: null,
      id: "13",
      level: 2,
      menuCode: "ASSIGNMENT_MANAGMENT",
      name: "任务管理",
      parentCode: "2",
      select: null,
      url: "/project/assignment",
    },
    {
      childMenuList: null,
      icon: null,
      id: "14",
      level: 2,
      menuCode: "PROGRESS_MANAGMENT",
      name: "阶段管理",
      parentCode: "2",
      select: null,
      url: "/device/ledger",
    },
    {
      childMenuList: null,
      icon: null,
      id: "15",
      level: 2,
      menuCode: "CHANGE_MANAGMENT",
      name: "变更管理",
      parentCode: "2",
      select: null,
      url: "/project/modifyMgt",
    },
]
const functionChild = [
      {
        childMenuList: null,
        icon: null,
        id: "16",
        level: 2,
        menuCode: "FUNCTION_DAY_REPORT_MANAGMENT",
        name: "职能日报管理",
        parentCode: "2",
        select: null,
        url: "/function/daily",
      },
      {
        childMenuList: null,
        icon: null,
        id: "17",
        level: 2,
        menuCode: "FUNCTION_ASSIGNMENT_MANAGMENT",
        name: "职能任务管理",
        parentCode: "2",
        select: null,

        url: "/device/ledger",
      },
]
const report = [
    {
      childMenuList: null,
      icon: null,
      id: "19",
      level: 2,
      menuCode: "HUMAN_REPORT_UNFINISHED",
      name: "人员报表-未完结",
      parentCode: "2",
      select: null,
      url: "/report/unfinishedReport",
    },
    {
      childMenuList: null,
      icon: null,
      id: "20",
      level: 2,
      menuCode: "HUMAN_REPORT_TIME",
      name: "人员报表-时间",
      parentCode: "2",
      select: null,
      url: "/device/ledger",
    },
    {
      childMenuList: null,
      icon: null,
      id: "21",
      level: 2,
      menuCode: "FINISHED_PROJECT_REPORT",
      name: "已完结项目报表",
      parentCode: "2",
      select: null,
      url: "/device/ledger",
    },
    {
      childMenuList: null,
      icon: null,
      id: "22",
      level: 2,
      menuCode: "DASHBOARD",
      name: "汇总看板",
      parentCode: "2",
      select: null,
      url: "/report/summaryBoard",
    },
]
// 列表
const premission = [
  {
    childMenuList: null,
    icon: null,
    id: "1",
    level: 1,
    menuCode: "MYBOARD",
    name: "我的看板",
    parentCode: "0",
    select: null,
    url: "/myBoard",
  },
  {
    icon: null,
    id: "2",
    level: 1,
    menuCode: "BASIC",
    name: "基础信息",
    parentCode: "0",
    select: null,
    url: "/basic",
    childMenuList: basic,
  },
  {
    icon: null,
    id: "3",
    level: 1,
    menuCode: "PROJECT",
    name: "项目管理",
    parentCode: "0",
    select: null,
    url: "/project",
    childMenuList: project
  },
  {
    icon: null,
    id: "4",
    level: 1,
    menuCode: "FUNCTION",
    name: "职能管理",
    parentCode: "0",
    select: null,
    url: "/function",
    childMenuList: functionChild
  },
  {
    icon: null,
    id: "5",
    level: 1,
    menuCode: "REPORT",
    name: "报表中心",
    parentCode: "0",
    select: null,
    url: "/report",
    childMenuList: report
  }
]
export default premission;